*;
/*----G_Customer_Age begin----*/
length _NORM2 $ 2;
_NORM2 = put( Customer_Age , BEST2. );
%DMNORMIP( _NORM2 )
drop _NORM2;
select(_NORM2);
when('26' ) G_Customer_Age = 9;
when('27' ) G_Customer_Age = 9;
when('28' ) G_Customer_Age = 10;
when('29' ) G_Customer_Age = 8;
when('30' ) G_Customer_Age = 2;
when('31' ) G_Customer_Age = 7;
when('32' ) G_Customer_Age = 6;
when('33' ) G_Customer_Age = 6;
when('34' ) G_Customer_Age = 8;
when('35' ) G_Customer_Age = 8;
when('36' ) G_Customer_Age = 8;
when('37' ) G_Customer_Age = 7;
when('38' ) G_Customer_Age = 6;
when('39' ) G_Customer_Age = 7;
when('40' ) G_Customer_Age = 4;
when('41' ) G_Customer_Age = 3;
when('42' ) G_Customer_Age = 7;
when('43' ) G_Customer_Age = 4;
when('44' ) G_Customer_Age = 5;
when('45' ) G_Customer_Age = 5;
when('46' ) G_Customer_Age = 5;
when('47' ) G_Customer_Age = 6;
when('48' ) G_Customer_Age = 4;
when('49' ) G_Customer_Age = 6;
when('50' ) G_Customer_Age = 6;
when('51' ) G_Customer_Age = 7;
when('52' ) G_Customer_Age = 6;
when('53' ) G_Customer_Age = 6;
when('54' ) G_Customer_Age = 2;
when('55' ) G_Customer_Age = 4;
when('56' ) G_Customer_Age = 5;
when('57' ) G_Customer_Age = 7;
when('58' ) G_Customer_Age = 6;
when('59' ) G_Customer_Age = 1;
when('60' ) G_Customer_Age = 8;
when('61' ) G_Customer_Age = 4;
when('62' ) G_Customer_Age = 4;
when('63' ) G_Customer_Age = 8;
when('64' ) G_Customer_Age = 8;
when('65' ) G_Customer_Age = 9;
when('66' ) G_Customer_Age = 0;
when('67' ) G_Customer_Age = 10;
when('68' ) G_Customer_Age = 0;
when('70' ) G_Customer_Age = 10;
when('73' ) G_Customer_Age = 10;
otherwise substr(_WARN_, 2, 1) = 'U';
end;
label G_Customer_Age="Grouped Levels for  Customer_Age";
/*----Customer_Age end----*/
