*;
/*----G_Months_on_book begin----*/
length _NORM2 $ 2;
_NORM2 = put( Months_on_book , BEST2. );
%DMNORMIP( _NORM2 )
drop _NORM2;
select(_NORM2);
when('13' ) G_Months_on_book = 7;
when('14' ) G_Months_on_book = 8;
when('15' ) G_Months_on_book = 0;
when('16' ) G_Months_on_book = 7;
when('17' ) G_Months_on_book = 7;
when('18' ) G_Months_on_book = 1;
when('19' ) G_Months_on_book = 8;
when('20' ) G_Months_on_book = 3;
when('21' ) G_Months_on_book = 7;
when('22' ) G_Months_on_book = 2;
when('23' ) G_Months_on_book = 7;
when('24' ) G_Months_on_book = 3;
when('25' ) G_Months_on_book = 2;
when('26' ) G_Months_on_book = 6;
when('27' ) G_Months_on_book = 7;
when('28' ) G_Months_on_book = 5;
when('29' ) G_Months_on_book = 6;
when('30' ) G_Months_on_book = 2;
when('31' ) G_Months_on_book = 7;
when('32' ) G_Months_on_book = 5;
when('33' ) G_Months_on_book = 5;
when('34' ) G_Months_on_book = 4;
when('35' ) G_Months_on_book = 6;
when('36' ) G_Months_on_book = 3;
when('37' ) G_Months_on_book = 3;
when('38' ) G_Months_on_book = 4;
when('39' ) G_Months_on_book = 2;
when('40' ) G_Months_on_book = 6;
when('41' ) G_Months_on_book = 3;
when('42' ) G_Months_on_book = 6;
when('43' ) G_Months_on_book = 5;
when('44' ) G_Months_on_book = 2;
when('45' ) G_Months_on_book = 6;
when('46' ) G_Months_on_book = 2;
when('47' ) G_Months_on_book = 6;
when('48' ) G_Months_on_book = 4;
when('49' ) G_Months_on_book = 3;
when('50' ) G_Months_on_book = 0;
when('51' ) G_Months_on_book = 2;
when('52' ) G_Months_on_book = 2;
when('53' ) G_Months_on_book = 8;
when('54' ) G_Months_on_book = 7;
when('55' ) G_Months_on_book = 8;
when('56' ) G_Months_on_book = 4;
otherwise substr(_WARN_, 2, 1) = 'U';
end;
label G_Months_on_book="Grouped Levels for  Months_on_book";
/*----Months_on_book end----*/
