*------------------------------------------------------------*;
* Computed Code;
*------------------------------------------------------------*;
*------------------------------------------------------------*;
* TRANSFORM: LOG_Total_Trans_Amt , (LOG_Total_Trans_Amt - 0) / (0.6931471806-0);
*------------------------------------------------------------*;
label RANGE_LOG_Total_Trans_Amt = 'Transformed: Transformed Total_Trans_Amt';
length RANGE_LOG_Total_Trans_Amt 8;
if LOG_Total_Trans_Amt eq . then RANGE_LOG_Total_Trans_Amt = .;
else RANGE_LOG_Total_Trans_Amt = (LOG_Total_Trans_Amt - 0) / (0.6931471806-0);
*------------------------------------------------------------*;
* TRANSFORM: SQRT_Avg_Utilization_Ratio , (SQRT_Avg_Utilization_Ratio - 0) / (1-0);
*------------------------------------------------------------*;
label RANGE_SQRT_Avg_Utilization_Ratio = 'Transformed: Transformed Avg_Utilization_Ratio';
length RANGE_SQRT_Avg_Utilization_Ratio 8;
if SQRT_Avg_Utilization_Ratio eq . then RANGE_SQRT_Avg_Utilization_Ratio = .;
else RANGE_SQRT_Avg_Utilization_Ratio = (SQRT_Avg_Utilization_Ratio - 0) / (1-0);
*------------------------------------------------------------*;
* TRANSFORM: SQRT_Total_Amt_Chng_Q4_Q1 , (SQRT_Total_Amt_Chng_Q4_Q1 - 0) / (1-0);
*------------------------------------------------------------*;
label RANGE_SQRT_Total_Amt_Chng_Q4_Q1 = 'Transformed: Transformed Total_Amt_Chng_Q4_Q1';
length RANGE_SQRT_Total_Amt_Chng_Q4_Q1 8;
if SQRT_Total_Amt_Chng_Q4_Q1 eq . then RANGE_SQRT_Total_Amt_Chng_Q4_Q1 = .;
else RANGE_SQRT_Total_Amt_Chng_Q4_Q1 = (SQRT_Total_Amt_Chng_Q4_Q1 - 0) / (1-0);
*------------------------------------------------------------*;
* TRANSFORM: SQRT_Total_Ct_Chng_Q4_Q1 , (SQRT_Total_Ct_Chng_Q4_Q1 - 0) / (1-0);
*------------------------------------------------------------*;
label RANGE_SQRT_Total_Ct_Chng_Q4_Q1 = 'Transformed: Transformed Total_Ct_Chng_Q4_Q1';
length RANGE_SQRT_Total_Ct_Chng_Q4_Q1 8;
if SQRT_Total_Ct_Chng_Q4_Q1 eq . then RANGE_SQRT_Total_Ct_Chng_Q4_Q1 = .;
else RANGE_SQRT_Total_Ct_Chng_Q4_Q1 = (SQRT_Total_Ct_Chng_Q4_Q1 - 0) / (1-0);
*------------------------------------------------------------*;
* TRANSFORM: Total_Revolving_Bal , (Total_Revolving_Bal - 0) / (2517-0);
*------------------------------------------------------------*;
label RANGE_Total_Revolving_Bal = 'Transformed Total_Revolving_Bal';
length RANGE_Total_Revolving_Bal 8;
if Total_Revolving_Bal eq . then RANGE_Total_Revolving_Bal = .;
else RANGE_Total_Revolving_Bal = (Total_Revolving_Bal - 0) / (2517-0);
