if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'AVG_OPEN_TO_BUY'
'AVG_UTILIZATION_RATIO'
'CARD_CATEGORY'
'CONTACTS_COUNT_12_MON'
'CREDIT_LIMIT'
'CUSTOMER_AGE'
'DEPENDENT_COUNT'
'EDUCATION_LEVEL'
'GENDER'
'INCOME_CATEGORY'
'MARITAL_STATUS'
'MONTHS_INACTIVE_12_MON'
'MONTHS_ON_BOOK'
'TOTAL_AMT_CHNG_Q4_Q1'
'TOTAL_CT_CHNG_Q4_Q1'
'TOTAL_RELATIONSHIP_COUNT'
'TOTAL_REVOLVING_BAL'
'TOTAL_TRANS_AMT'
'TOTAL_TRANS_CT'
) then ROLE='INPUT';
else delete;
end;
